[package]
name = "star-history"
version = "0.1.3"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Graph history of GitHub stars of a user or repo over time"
repository = "https://github.com/dtolnay/star-history"
readme = "README.md"
exclude = ["screenshots"]

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
opener = "0.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
